# -*- coding: utf-8 -*-
"""CMSS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lQrEDwPLxGAah4Hb3HuJzFNLO1kQrqIu

Problem Description:
Customer support teams receive a large volume of unstructured email tickets containing diverse issues such as technical problems, service requests, and complaints. Manually analyzing and routing these emails is time-consuming, error-prone, and inefficient, especially at scale.

This project aims to build an NLP-driven system that automatically converts raw email text into structured insights by performing multi-task classification and semantic retrieval.[link](https://huggingface.co/datasets/Tobi-Bueck/customer-support-tickets)

# Preprocessing
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from itertools import product

from datasets import load_dataset

dataset = load_dataset("Tobi-Bueck/customer-support-tickets", split="train")
df = pd.DataFrame(dataset)
df.head()

df = df[df['language'] == 'en']
df = df.drop(columns=['language', 'version'])
df.reset_index(drop=True, inplace=True)

tag_cols = [f'tag_{i}' for i in range(1,9)]
df['tags'] = df[tag_cols].values.tolist()
df['tags'] = df['tags'].apply(lambda x: [t for t in x if t is not None])
df = df.drop(columns=tag_cols)

# Combine subject + body
df['text'] = df['subject'].fillna('') + ' ' + df['body'].fillna('')
df = df.drop(columns=['subject', 'body'])

print(df.info())
print(df.describe(include='all'))

# Count unique classes
for col in ['type','queue','priority']:
    print(f"{col}: {df[col].nunique()} unique values")
    print(df[col].value_counts().head(10))

print(df.isnull().sum())

all_tags = [t for tags in df['tags'] for t in tags]
tags_series = pd.Series(all_tags)
tags_series.value_counts().head(20).plot(kind='barh', figsize=(10,6))
plt.title("Top 20 Tags")
plt.show()

from sklearn.preprocessing import LabelEncoder

le_type = LabelEncoder()
le_priority = LabelEncoder()
le_queue = LabelEncoder()

df['type_enc'] = le_type.fit_transform(df['type'])
df['priority_enc'] = le_priority.fit_transform(df['priority'])
df['queue_enc'] = le_queue.fit_transform(df['queue'])

corr_cols = ['type_enc','priority_enc','queue_enc']
corr = df[corr_cols].corr()
sns.heatmap(corr, annot=True, cmap='coolwarm')
plt.title("Correlation Matrix between type, priority, queue")
plt.show()

combinations = list(product(df['type'].unique(), df['priority'].unique(), df['queue'].unique()))
comb_df = pd.DataFrame(combinations, columns=['type','priority','queue'])

# Merge with counts in dataset
counts = df.groupby(['type','priority','queue']).size().reset_index(name='count')
comb_df = comb_df.merge(counts, on=['type','priority','queue'], how='left').fillna(0)
comb_df.head(10)

df['text_len'] = df['text'].apply(len)
df['answer_len'] = df['answer'].fillna('').apply(len)

sns.histplot(df['text_len'], bins=50, kde=True)
plt.title("Email Text Length Distribution")
plt.show()

sns.histplot(df['answer_len'], bins=50, kde=True)
plt.title("Answer Text Length Distribution")
plt.show()

df['num_tags'] = df['tags'].apply(len)
sns.histplot(df['num_tags'], bins=8, discrete=True)
plt.title("Number of Tags per Email")
plt.show()

queue_counts = df['queue'].value_counts()
plt.figure(figsize=(12,6))
sns.barplot(x=queue_counts.index[:20], y=queue_counts.values[:20])
plt.xticks(rotation=90)
plt.title("Top 20 Queue Counts")
plt.show()

from collections import Counter
tag_combos = df['tags'].apply(lambda x: tuple(sorted(x)))
Counter(tag_combos).most_common(10)

import re

def clean_text(text):
    text = text.lower()
    text = re.sub(r'\s+',' ', text)
    text = re.sub(r'[^a-z0-9 .,?!]', '', text)
    return text

df['text_clean'] = df['text'].apply(clean_text)
df['answer_clean'] = df['answer'].fillna('').apply(clean_text)

df.to_csv("customer_support_cleaned.csv", index=False)

"""# TEST_TRAIN"""

from sklearn.model_selection import train_test_split

train_df, test_df = train_test_split(
    df,
    test_size=0.2,
    stratify=df['type'],
    random_state=42
)

train_df = train_df.reset_index(drop=True)
test_df = test_df.reset_index(drop=True)

!pip install sentence-transformers

# Cell 18: Embedding-based features
from sentence_transformers import SentenceTransformer

embed_model = SentenceTransformer('all-MiniLM-L6-v2')

# Generate embeddings
X_train = embed_model.encode(
    train_df['text_clean'].tolist(),
    show_progress_bar=True
)

X_test = embed_model.encode(
    test_df['text_clean'].tolist(),
    show_progress_bar=True
)

y_train_type = train_df['type']
y_test_type = test_df['type']

y_train_priority = train_df['priority']
y_test_priority = test_df['priority']

y_train_queue = train_df['queue']
y_test_queue = test_df['queue']

from sklearn.linear_model import LogisticRegression

type_model = LogisticRegression(max_iter=1000)
type_model.fit(X_train, y_train_type)

priority_model = LogisticRegression(max_iter=1000)
priority_model.fit(X_train, y_train_priority)

queue_model = LogisticRegression(max_iter=1000, class_weight='balanced')
queue_model.fit(X_train, y_train_queue)

"""# Evaluation metrix"""

from sklearn.metrics import classification_report

# TYPE
print("TYPE MODEL")
print(classification_report(y_test_type, type_model.predict(X_test)))

# PRIORITY
print("PRIORITY MODEL")
print(classification_report(y_test_priority, priority_model.predict(X_test)))

# QUEUE
print("QUEUE MODEL")
print(classification_report(y_test_queue, queue_model.predict(X_test)))

from sklearn.preprocessing import MultiLabelBinarizer

mlb = MultiLabelBinarizer()

y_train_tags = mlb.fit_transform(train_df['tags'])
y_test_tags = mlb.transform(test_df['tags'])

from sklearn.multiclass import OneVsRestClassifier

tag_model = OneVsRestClassifier(LogisticRegression(max_iter=1000))
tag_model.fit(X_train, y_train_tags)

from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay

import matplotlib.pyplot as plt

def plot_conf_matrix(y_true, y_pred, title):
    cm = confusion_matrix(y_true, y_pred)
    disp = ConfusionMatrixDisplay(confusion_matrix=cm)

    fig, ax = plt.subplots(figsize=(6,6))
    disp.plot(ax=ax, cmap='Blues', xticks_rotation=45)
    plt.title(title)
    plt.show()

# TYPE
plot_conf_matrix(y_test_type, type_model.predict(X_test), "Type Confusion Matrix")

# PRIORITY
plot_conf_matrix(y_test_priority, priority_model.predict(X_test), "Priority Confusion Matrix")

top_queues = train_df['queue'].value_counts().head(10).index

mask = test_df['queue'].isin(top_queues)

y_true_top = y_test_queue[mask]
y_pred_top = queue_model.predict(X_test[mask])

plot_conf_matrix(y_true_top, y_pred_top, "Queue Confusion Matrix (Top 10)")

from sklearn.metrics import classification_report

def print_class_report(y_true, y_pred, title):
    print(f"\n===== {title} =====\n")
    print(classification_report(y_true, y_pred))

# TYPE
print_class_report(y_test_type, type_model.predict(X_test), "TYPE REPORT")

# PRIORITY
print_class_report(y_test_priority, priority_model.predict(X_test), "PRIORITY REPORT")

# QUEUE
print_class_report(y_test_queue, queue_model.predict(X_test), "QUEUE REPORT")

"""# Semantic retrival"""

!pip install sentence-transformers

from sentence_transformers import SentenceTransformer

embed_model = SentenceTransformer('all-MiniLM-L6-v2')

train_embeddings = embed_model.encode(train_df['text_clean'], show_progress_bar=True)

from sklearn.metrics.pairwise import cosine_similarity

def retrieve_best_answer(query):
    query_emb = embed_model.encode([query])
    sims = cosine_similarity(query_emb, train_embeddings)[0]

    top_idx = sims.argmax()
    best_match = train_df.iloc[top_idx]

    return {
        "similarity_score": float(sims[top_idx]),
        "matched_text": best_match['text_clean'],
        "answer": best_match['answer']
    }

def predict_ticket(text):
    text_clean = text.lower()

    vec = embed_model.encode([text_clean])

    best_match = retrieve_best_answer(text)

    result = {
        "type": type_model.predict(vec)[0],
        "priority": priority_model.predict(vec)[0],
        "queue": queue_model.predict(vec)[0],
        "tags": mlb.inverse_transform(tag_model.predict(vec))[0],
        "best_match": best_match
    }

    return result

def pretty_print_prediction(result, query):
    print("\n===== YOUR QUERY =====\n")
    print(query)

    print("\n===== PREDICTION =====\n")
    print(f"Type      : {result['type']}")
    print(f"Priority  : {result['priority']}")
    print(f"Queue     : {result['queue']}")
    print(f"Tags      : {', '.join(result['tags'])}")

    print("\n===== MATCHED PAST CASE =====\n")
    print(result['best_match']['matched_text'])

    print("\n===== SUGGESTED RESPONSE =====\n")
    print(result['best_match']['answer'])

    print("\n===== CONFIDENCE =====")
    print(f"Similarity Score: {result['best_match']['similarity_score']:.3f}")

sample_text = test_df.loc[2089, 'text_clean']

result = predict_ticket(sample_text)

pretty_print_prediction(result, sample_text)